import { useState } from "react";
import { Link } from "react-router-dom";
import { useApi } from "../hooks/useApi";
import { getFollowups, completeFollowup, getRiskAssessments } from "../api/client";
import type { Followup, RiskAssessment } from "../types";
import { SkeletonCard } from "./ui/Skeleton";
import EmptyState from "./ui/EmptyState";
import {
  ClipboardList,
  RefreshCw,
  Calendar,
  TestTube2,
  Phone,
  AlertTriangle,
  CheckCircle2,
  Clock,
} from "lucide-react";
import { formatDate, formatRelativeDate } from "../utils/dates";

type FollowupRow = Followup & {
  fname?: string;
  lname?: string;
  insurance_type?: string;
};

const TYPE_CONFIG: Record<
  string,
  { bg: string; label: string; icon: typeof Calendar }
> = {
  schedule_visit: {
    bg: "bg-blue-100 text-blue-800",
    label: "Schedule Visit",
    icon: Calendar,
  },
  order_lab: {
    bg: "bg-purple-100 text-purple-800",
    label: "Order Lab",
    icon: TestTube2,
  },
  call_patient: {
    bg: "bg-green-100 text-green-800",
    label: "Call Patient",
    icon: Phone,
  },
};

const INSURANCE_STYLES: Record<string, string> = {
  medicare: "bg-blue-100 text-blue-800",
  medicaid: "bg-purple-100 text-purple-800",
  commercial: "bg-teal-100 text-teal-800",
};

/** Pull a human-readable summary from a followup's payload_json. */
function summarizePayload(payload: Record<string, unknown>): string {
  const parts: string[] = [];

  // "reason" field from risk-engine followups
  if (typeof payload.reason === "string") parts.push(payload.reason);
  // "test" field from lab-order followups
  if (typeof payload.test === "string") parts.push(`Lab: ${payload.test}`);
  // "subject" from email outreach
  if (typeof payload.subject === "string") parts.push(payload.subject);
  // "message" from outreach / calls
  if (typeof payload.message === "string" && !payload.subject)
    parts.push(payload.message);

  // Extract key details from the "evidence" sub-object
  if (payload.evidence && typeof payload.evidence === "object") {
    const ev = payload.evidence as Record<string, unknown>;
    if (ev.status === "no_bp_recorded") {
      parts.push("No BP on file");
    } else if (ev.bps && ev.bpd) {
      parts.push(`BP ${ev.bps}/${ev.bpd}`);
    }
    if (ev.value) parts.push(`A1c ${ev.value}%`);
    if (ev.message && typeof ev.message === "string") parts.push(ev.message);
  }

  if (parts.length === 0) {
    // Generic fallback — show top-level string values, skip objects
    return Object.entries(payload)
      .filter(([k]) => k !== "patient")
      .map(([, v]) => (typeof v === "string" ? v : null))
      .filter(Boolean)
      .join(" — ") || "—";
  }
  return parts.join(" — ");
}

export default function FollowupTracker() {
  const [filter, setFilter] = useState<{
    status: string;
    task_type: string;
  }>({ status: "open", task_type: "" });

  const { data, loading, error, refetch } = useApi(
    () =>
      getFollowups({
        status: filter.status || undefined,
        task_type: filter.task_type || undefined,
        limit: 50,
      }),
    [filter.status, filter.task_type]
  );

  const { data: assessData } = useApi(
    () => getRiskAssessments({ limit: 200 }),
    []
  );

  // Build PID → patient info lookup from assessments
  const patientMap = new Map<
    number,
    { fname: string; lname: string; insurance_type?: string }
  >();
  const assessments = (assessData?.data || []) as (RiskAssessment & {
    fname?: string;
    lname?: string;
    insurance_type?: string;
  })[];
  for (const a of assessments) {
    if (!patientMap.has(a.pid)) {
      patientMap.set(a.pid, {
        fname: a.fname || "",
        lname: a.lname || "",
        insurance_type: a.insurance_type,
      });
    }
  }

  const followups = (data?.data || []) as FollowupRow[];

  async function handleComplete(id: number) {
    try {
      await completeFollowup(id);
      refetch();
    } catch {
      // ignore
    }
  }

  return (
    <div className="space-y-4 animate-fade-in">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <ClipboardList className="w-5 h-5 text-clinical-600" />
          <div>
            <h2 className="text-lg font-bold text-gray-900">
              Followup Tracker
            </h2>
            <p className="text-xs text-gray-500">
              Track and manage pending care tasks — scheduled visits, lab
              orders, and patient calls generated by risk alerts and agent
              recommendations. Mark tasks complete as they are addressed.
            </p>
          </div>
        </div>
        <button
          onClick={refetch}
          className="btn-secondary text-xs !px-3 !py-1.5"
        >
          <RefreshCw className="w-3.5 h-3.5" />
        </button>
      </div>

      {/* Filters */}
      <div className="flex gap-3">
        <div>
          <label className="block text-[10px] font-medium text-gray-500 uppercase tracking-wider mb-1">
            Status
          </label>
          <select
            value={filter.status}
            onChange={(e) =>
              setFilter((f) => ({ ...f, status: e.target.value }))
            }
            className="select-clinical"
          >
            <option value="open">Open</option>
            <option value="completed">Completed</option>
            <option value="cancelled">Cancelled</option>
            <option value="">All</option>
          </select>
        </div>
        <div>
          <label className="block text-[10px] font-medium text-gray-500 uppercase tracking-wider mb-1">
            Type
          </label>
          <select
            value={filter.task_type}
            onChange={(e) =>
              setFilter((f) => ({ ...f, task_type: e.target.value }))
            }
            className="select-clinical"
          >
            <option value="">All Types</option>
            <option value="schedule_visit">Schedule Visit</option>
            <option value="order_lab">Order Lab</option>
            <option value="call_patient">Call Patient</option>
          </select>
        </div>
      </div>

      {loading && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
          {[1, 2, 3, 4].map((i) => (
            <SkeletonCard key={i} />
          ))}
        </div>
      )}

      {error && (
        <div className="flex flex-col items-center justify-center py-12 gap-3">
          <div className="w-12 h-12 rounded-full bg-red-50 flex items-center justify-center">
            <AlertTriangle className="w-6 h-6 text-red-500" />
          </div>
          <p className="text-sm text-gray-600">{error}</p>
          <button onClick={refetch} className="btn-secondary text-xs">
            Retry
          </button>
        </div>
      )}

      {!loading && !error && followups.length === 0 && (
        <EmptyState preset="followups" />
      )}

      {/* Task table — grouped by type */}
      {!loading && followups.length > 0 && (
        <div className="space-y-5">
          {(["schedule_visit", "order_lab", "call_patient"] as const)
            .map((type) => {
              const group = followups.filter((f) => f.task_type === type);
              if (group.length === 0) return null;
              const config = TYPE_CONFIG[type];
              const GroupIcon = config.icon;
              return (
                <div key={type}>
                  <div className="flex items-center gap-2 mb-2">
                    <div
                      className={`w-6 h-6 rounded flex items-center justify-center ${config.bg}`}
                    >
                      <GroupIcon className="w-3.5 h-3.5" />
                    </div>
                    <h3 className="text-sm font-semibold text-gray-700">
                      {config.label}
                    </h3>
                    <span className="text-xs text-gray-400">
                      ({group.length})
                    </span>
                  </div>
                  <div className="card overflow-hidden">
                    <table className="w-full text-sm">
                      <thead className="bg-gray-50 border-b border-gray-200">
                        <tr>
                          <th className="px-4 py-2 text-left text-[10px] font-semibold text-gray-500 uppercase tracking-wider">
                            Patient
                          </th>
                          <th className="px-4 py-2 text-left text-[10px] font-semibold text-gray-500 uppercase tracking-wider">
                            Insurance
                          </th>
                          <th className="px-4 py-2 text-center text-[10px] font-semibold text-gray-500 uppercase tracking-wider">
                            Details
                          </th>
                          <th className="px-4 py-2 text-center text-[10px] font-semibold text-gray-500 uppercase tracking-wider">
                            Due
                          </th>
                          <th className="px-4 py-2 text-left text-[10px] font-semibold text-gray-500 uppercase tracking-wider">
                            Created
                          </th>
                          <th className="px-4 py-2 text-right text-[10px] font-semibold text-gray-500 uppercase tracking-wider">
                            Status
                          </th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-gray-100">
                        {group.map((f) => {
                          const overdue =
                            f.due_date &&
                            f.status === "open" &&
                            new Date(f.due_date) < new Date();
                          const info = patientMap.get(f.pid);
                          const patientName =
                            info && (info.fname || info.lname)
                              ? `${info.lname}, ${info.fname}`
                              : (f.payload_json?.patient as string) || null;
                          const insurance = info?.insurance_type;
                          const details = f.payload_json
                            ? summarizePayload(f.payload_json)
                            : "";

                          return (
                            <tr
                              key={f.id}
                              className={`transition-colors cursor-default hover:bg-gray-100 ${
                                overdue ? "bg-red-50/50" : ""
                              }`}
                            >
                              {/* Patient name + PID */}
                              <td className="px-4 py-2.5">
                                <Link
                                  to={`/patients/${f.pid}`}
                                  className="block text-sm font-medium text-gray-900 hover:text-clinical-700 transition-colors"
                                >
                                  {patientName || `PID ${f.pid}`}
                                </Link>
                                <span className="font-mono text-[10px] text-gray-400">
                                  PID {f.pid}
                                </span>
                              </td>

                              {/* Insurance */}
                              <td className="px-4 py-2.5">
                                {insurance ? (
                                  <span
                                    className={`px-1.5 py-0.5 rounded text-[10px] font-semibold uppercase ${
                                      INSURANCE_STYLES[insurance] ||
                                      "bg-gray-100 text-gray-600"
                                    }`}
                                  >
                                    {insurance}
                                  </span>
                                ) : (
                                  <span className="text-xs text-gray-400">
                                    —
                                  </span>
                                )}
                              </td>

                              {/* Details */}
                              <td className="px-4 py-2.5 text-xs text-gray-700 max-w-xs truncate text-center">
                                {details || "—"}
                              </td>

                              {/* Due date */}
                              <td className="px-4 py-2.5 whitespace-nowrap text-center">
                                {f.due_date ? (
                                  <span
                                    className={`inline-flex items-center gap-1 text-xs ${
                                      overdue
                                        ? "text-red-600 font-medium"
                                        : "text-gray-500"
                                    }`}
                                  >
                                    {overdue ? (
                                      <AlertTriangle className="w-3 h-3" />
                                    ) : (
                                      <Clock className="w-3 h-3" />
                                    )}
                                    {overdue ? "OVERDUE " : ""}
                                    {formatDate(f.due_date)}
                                  </span>
                                ) : (
                                  <span className="text-xs text-gray-400">
                                    —
                                  </span>
                                )}
                              </td>

                              {/* Created */}
                              <td className="px-4 py-2.5 text-xs text-gray-400 whitespace-nowrap">
                                {formatRelativeDate(f.created_at)}
                              </td>

                              {/* Status / Action */}
                              <td className="px-4 py-2.5 text-right">
                                {f.status === "open" && (
                                  <button
                                    onClick={() => handleComplete(f.id)}
                                    className="inline-flex items-center gap-1 px-2 py-0.5 text-xs bg-green-100 hover:bg-green-200 text-green-700 rounded-md transition-colors"
                                  >
                                    <CheckCircle2 className="w-3 h-3" />
                                    {f.task_type === "order_lab" ? "Ordered" : "Complete"}
                                  </button>
                                )}
                                {f.status === "completed" && (
                                  <span className="inline-flex items-center gap-1 text-xs text-green-600 font-medium">
                                    <CheckCircle2 className="w-3 h-3" />
                                    Done
                                  </span>
                                )}
                                {f.status === "cancelled" && (
                                  <span className="text-xs text-gray-400 italic">
                                    Cancelled
                                  </span>
                                )}
                              </td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                </div>
              );
            })
            .filter(Boolean)}
        </div>
      )}
    </div>
  );
}
